### PR TITLE
createAngularProject

### PR DESCRIPTION
**Pull request by Romaus**
init angularProject

### CODE REVIEW

**Comment by Darya2311** [comment]
Review was completed.

**Comment by Alekskarb** [comment]
Review is done

**Comment by ViktorRiabinin** [comment]
Please place project in a root folder of the repository. Get rid of duplication of README and gitignore files

**Review by Alekskarb — COMMENTED** [review]
Review completed

**Review by Darya2311 — COMMENTED** [review]
Review was completed.

**Review by Darya2311 — COMMENTED** [review]
refactor: extra files deleted.

**Review by Alekskarb — COMMENTED** [review]
files refactored

**Review by ViktorRiabinin — APPROVED** [review]

**Review by Alekskarb — APPROVED** [review]

**Review by Darya2311 — APPROVED** [review]

**Pull request merged**
